#!/bin/bash

hostnamectl set-hostname ${fqdn}

yum -y update
yum -y install wget unzip

echo Creating /etc/sysconfig/iptables...
cat <<EOFEOF >/etc/sysconfig/iptables
# Generated by iptables-save v1.4.21 on Fri Jun 17 04:03:09 2016
*nat
:PREROUTING  ACCEPT [0:0]
:INPUT       ACCEPT [0:0]
:OUTPUT      ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A PREROUTING -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 8443
COMMIT
# Completed on Fri Jun 17 04:03:09 2016

# Generated by iptables-save v1.4.21 on Fri Jun 17 04:03:09 2016
*filter
:INPUT   ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT  ACCEPT [0:0]
COMMIT
# Completed on Fri Jun 17 04:03:09 2016
EOFEOF

echo Applying new iptables...
iptables-restore </etc/sysconfig/iptables

##
## install oracle java
##
fn="jdk-8u91-linux-x64"
wget -c --no-cookies --no-check-certificate \
 --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
 "http://download.oracle.com/otn-pub/java/jdk/8u91-b14/$fn.rpm" \
 --output-document="/tmp/$fn.rpm"

yum -y localinstall /tmp/jdk-8u91-linux-x64.rpm

echo export JAVA_HOME=/usr/java/jdk1.8.0_91 >> /etc/profile

##
## adjust JCE Policy to unlimited
##
wget -q -c --no-cookies --no-check-certificate \
 --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
 "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip" \
 --output-document="/tmp/jce_policy-8.zip"

unzip /tmp/jce_policy-8.zip -d /opt
cp -f /opt/UnlimitedJCEPolicyJDK8/*jar /usr/java/jdk1.8.0_91/jre/lib/security/

##
## install jetty
##
fn="jetty-distribution-9.3.9.v20160517"
wget -q -c --no-cookies --no-check-certificate \
  "http://eclipse.org/downloads/download.php?file=/jetty/stable-9/dist/$fn.tar.gz&r=1" \
  --output-document="/tmp/$fn.tar.gz"

tar xzf /tmp/$fn.tar.gz -C /opt

##
## configure jetty
##
cd /opt

echo ln -vs $fn jetty
ln -vs $fn jetty

echo useradd -m jetty
useradd -m jetty

echo chown -vR jetty:jetty /opt/jetty/
chown -vR jetty:jetty /opt/jetty/

echo cp -v /opt/jetty/bin/jetty.sh /etc/init.d/jetty
cp -v /opt/jetty/bin/jetty.sh /etc/init.d/jetty

echo chkconfig --add jetty
chkconfig --add jetty

echo chkconfig --level 345 jetty on
chkconfig --level 345 jetty on

echo Creating /etc/default/jetty...
cat <<EOFEOF >/etc/default/jetty
JETTY_HOME=/opt/jetty
JETTY_USER=jetty
JETTY_PORT=80
JETTY_HOST=0.0.0.0
JETTY_LOGS=/opt/jetty/logs/
EOFEOF
cat /etc/default/jetty

#service jetty start

##
## install shibboleth-identity-provider
##
ver="3.2.1"
fn="shibboleth-identity-provider-$ver"
wget -q -c --no-cookies --no-check-certificate \
  "https://shibboleth.net/downloads/identity-provider/3.2.1/$fn.tar.gz" \
  --output-document="/tmp/$fn.tar.gz"

tar xzf /tmp/$fn.tar.gz -C /opt
